package com.roamguard.mcc

object MccDataset {
    private val entries_: List<MccEntry> by lazy {
        listOf(
            MccEntry(202, countryCode = "GR", countryName = "Greece"),
            MccEntry(204, countryCode = "NL", countryName = "Netherlands"),
            MccEntry(206, countryCode = "BE", countryName = "Belgium"),
            MccEntry(208, countryCode = "FR", countryName = "France"),
            MccEntry(212, countryCode = "MC", countryName = "Monaco"),
            MccEntry(213, countryCode = "AD", countryName = "Andorra"),
            MccEntry(214, countryCode = "ES", countryName = "Spain"),
            MccEntry(216, countryCode = "HU", countryName = "Hungary"),
            MccEntry(218, countryCode = "BA", countryName = "Bosnia and Herzegovina"),
            MccEntry(219, countryCode = "HR", countryName = "Croatia"),
            MccEntry(220, countryCode = "RS", countryName = "Serbia"),
            MccEntry(222, countryCode = "IT", countryName = "Italy"),
            MccEntry(225, countryCode = "VA", countryName = "Vatican City"),
            MccEntry(226, countryCode = "RO", countryName = "Romania"),
            MccEntry(228, countryCode = "CH", countryName = "Switzerland"),
            MccEntry(230, countryCode = "CZ", countryName = "Czech Republic"),
            MccEntry(231, countryCode = "SK", countryName = "Slovakia"),
            MccEntry(232, countryCode = "AT", countryName = "Austria"),
            MccEntry(234, countryCode = "GB", countryName = "United Kingdom"),
            MccEntry(238, countryCode = "DK", countryName = "Denmark"),
            MccEntry(240, countryCode = "SE", countryName = "Sweden"),
            MccEntry(242, countryCode = "NO", countryName = "Norway"),
            MccEntry(244, countryCode = "FI", countryName = "Finland"),
            MccEntry(246, countryCode = "LT", countryName = "Lithuania"),
            MccEntry(247, countryCode = "LV", countryName = "Latvia"),
            MccEntry(248, countryCode = "EE", countryName = "Estonia"),
            MccEntry(250, countryCode = "RU", countryName = "Russia"),
            MccEntry(255, countryCode = "UA", countryName = "Ukraine"),
            MccEntry(257, countryCode = "BY", countryName = "Belarus"),
            MccEntry(259, countryCode = "MD", countryName = "Moldova"),
            MccEntry(260, countryCode = "PL", countryName = "Poland"),
            MccEntry(262, countryCode = "DE", countryName = "Germany"),
            MccEntry(266, countryCode = "GI", countryName = "Gibraltar"),
            MccEntry(268, countryCode = "PT", countryName = "Portugal"),
            MccEntry(270, countryCode = "LU", countryName = "Luxembourg"),
            MccEntry(272, countryCode = "IE", countryName = "Ireland"),
            MccEntry(274, countryCode = "IS", countryName = "Iceland"),
            MccEntry(276, countryCode = "AL", countryName = "Albania"),
            MccEntry(278, countryCode = "MT", countryName = "Malta"),
            MccEntry(280, countryCode = "CY", countryName = "Cyprus"),
            MccEntry(282, countryCode = "GE", countryName = "Georgia"),
            MccEntry(283, countryCode = "AM", countryName = "Armenia"),
            MccEntry(284, countryCode = "BG", countryName = "Bulgaria"),
            MccEntry(286, countryCode = "TR", countryName = "Turkey"),
            MccEntry(288, countryCode = "FO", countryName = "Faroe Islands"),
            MccEntry(290, countryCode = "GL", countryName = "Greenland"),
            MccEntry(292, countryCode = "SM", countryName = "San Marino"),
            MccEntry(293, countryCode = "SI", countryName = "Slovenia"),
            MccEntry(294, countryCode = "MK", countryName = "North Macedonia"),
            MccEntry(295, countryCode = "LI", countryName = "Liechtenstein"),
            MccEntry(297, countryCode = "ME", countryName = "Montenegro"),
            MccEntry(302, countryCode = "CA", countryName = "Canada"),
            MccEntry(308, countryCode = "PM", countryName = "Saint Pierre and Miquelon"),
            MccEntry(310, countryCode = "US", countryName = "United States"),
            MccEntry(311, countryCode = "US", countryName = "United States"),
            MccEntry(312, countryCode = "US", countryName = "United States"),
            MccEntry(313, countryCode = "US", countryName = "United States"),
            MccEntry(314, countryCode = "US", countryName = "United States"),
            MccEntry(315, countryCode = "US", countryName = "United States"),
            MccEntry(316, countryCode = "US", countryName = "United States"),
            MccEntry(330, countryCode = "PR", countryName = "Puerto Rico"),
            MccEntry(332, countryCode = "VI", countryName = "U.S. Virgin Islands"),
            MccEntry(334, countryCode = "MX", countryName = "Mexico"),
            MccEntry(338, countryCode = "JM", countryName = "Jamaica"),
            MccEntry(340, countryCode = "GP", countryName = "Guadeloupe"),
            MccEntry(342, countryCode = "BB", countryName = "Barbados"),
            MccEntry(344, countryCode = "AG", countryName = "Antigua and Barbuda"),
            MccEntry(346, countryCode = "KY", countryName = "Cayman Islands"),
            MccEntry(348, countryCode = "VG", countryName = "British Virgin Islands"),
            MccEntry(350, countryCode = "BM", countryName = "Bermuda"),
            MccEntry(352, countryCode = "GD", countryName = "Grenada"),
            MccEntry(354, countryCode = "MS", countryName = "Montserrat"),
            MccEntry(356, countryCode = "KN", countryName = "Saint Kitts and Nevis"),
            MccEntry(358, countryCode = "LC", countryName = "Saint Lucia"),
            MccEntry(360, countryCode = "VC", countryName = "Saint Vincent and the Grenadines"),
            MccEntry(362, countryCode = "AI", countryName = "Anguilla"),
            MccEntry(363, countryCode = "AW", countryName = "Aruba"),
            MccEntry(364, countryCode = "BS", countryName = "Bahamas"),
            MccEntry(365, countryCode = "AI", countryName = "Anguilla"),
            MccEntry(366, countryCode = "DM", countryName = "Dominica"),
            MccEntry(368, countryCode = "CU", countryName = "Cuba"),
            MccEntry(370, countryCode = "DO", countryName = "Dominican Republic"),
            MccEntry(372, countryCode = "HT", countryName = "Haiti"),
            MccEntry(374, countryCode = "TT", countryName = "Trinidad and Tobago"),
            MccEntry(376, countryCode = "TC", countryName = "Turks and Caicos Islands"),
            MccEntry(400, countryCode = "AZ", countryName = "Azerbaijan"),
            MccEntry(401, countryCode = "KZ", countryName = "Kazakhstan"),
            MccEntry(402, countryCode = "BT", countryName = "Bhutan"),
            MccEntry(404, countryCode = "IN", countryName = "India"),
            MccEntry(405, countryCode = "IN", countryName = "India"),
            MccEntry(410, countryCode = "PK", countryName = "Pakistan"),
            MccEntry(412, countryCode = "AF", countryName = "Afghanistan"),
            MccEntry(413, countryCode = "LK", countryName = "Sri Lanka"),
            MccEntry(414, countryCode = "MM", countryName = "Myanmar"),
            MccEntry(415, countryCode = "LB", countryName = "Lebanon"),
            MccEntry(416, countryCode = "JO", countryName = "Jordan"),
            MccEntry(417, countryCode = "SY", countryName = "Syria"),
            MccEntry(418, countryCode = "IQ", countryName = "Iraq"),
            MccEntry(419, countryCode = "KW", countryName = "Kuwait"),
            MccEntry(420, countryCode = "SA", countryName = "Saudi Arabia"),
            MccEntry(421, countryCode = "YE", countryName = "Yemen"),
            MccEntry(422, countryCode = "OM", countryName = "Oman"),
            MccEntry(423, countryCode = "PS", countryName = "Palestine"),
            MccEntry(424, countryCode = "AE", countryName = "United Arab Emirates"),
            MccEntry(425, countryCode = "IL", countryName = "Israel"),
            MccEntry(426, countryCode = "BH", countryName = "Bahrain"),
            MccEntry(427, countryCode = "QA", countryName = "Qatar"),
            MccEntry(428, countryCode = "MN", countryName = "Mongolia"),
            MccEntry(429, countryCode = "NP", countryName = "Nepal"),
            MccEntry(432, countryCode = "IR", countryName = "Iran"),
            MccEntry(434, countryCode = "UZ", countryName = "Uzbekistan"),
            MccEntry(436, countryCode = "TJ", countryName = "Tajikistan"),
            MccEntry(437, countryCode = "KG", countryName = "Kyrgyzstan"),
            MccEntry(438, countryCode = "TM", countryName = "Turkmenistan"),
            MccEntry(440, countryCode = "JP", countryName = "Japan"),
            MccEntry(441, countryCode = "JP", countryName = "Japan"),
            MccEntry(450, countryCode = "KR", countryName = "South Korea"),
            MccEntry(452, countryCode = "VN", countryName = "Vietnam"),
            MccEntry(454, countryCode = "HK", countryName = "Hong Kong"),
            MccEntry(455, countryCode = "MO", countryName = "Macau"),
            MccEntry(456, countryCode = "KH", countryName = "Cambodia"),
            MccEntry(457, countryCode = "LA", countryName = "Laos"),
            MccEntry(460, countryCode = "CN", countryName = "China"),
            MccEntry(461, countryCode = "CN", countryName = "China"),
            MccEntry(466, countryCode = "TW", countryName = "Taiwan"),
            MccEntry(467, countryCode = "KP", countryName = "North Korea"),
            MccEntry(470, countryCode = "BD", countryName = "Bangladesh"),
            MccEntry(472, countryCode = "MV", countryName = "Maldives"),
            MccEntry(502, countryCode = "MY", countryName = "Malaysia"),
            MccEntry(505, countryCode = "AU", countryName = "Australia"),
            MccEntry(510, countryCode = "ID", countryName = "Indonesia"),
            MccEntry(514, countryCode = "TL", countryName = "Timor-Leste"),
            MccEntry(515, countryCode = "PH", countryName = "Philippines"),
            MccEntry(520, countryCode = "TH", countryName = "Thailand"),
            MccEntry(525, countryCode = "SG", countryName = "Singapore"),
            MccEntry(528, countryCode = "BN", countryName = "Brunei"),
            MccEntry(530, countryCode = "NZ", countryName = "New Zealand"),
            MccEntry(536, countryCode = "NR", countryName = "Nauru"),
            MccEntry(537, countryCode = "PG", countryName = "Papua New Guinea"),
            MccEntry(539, countryCode = "TO", countryName = "Tonga"),
            MccEntry(540, countryCode = "SB", countryName = "Solomon Islands"),
            MccEntry(541, countryCode = "VU", countryName = "Vanuatu"),
            MccEntry(542, countryCode = "FJ", countryName = "Fiji"),
            MccEntry(543, countryCode = "WF", countryName = "Wallis and Futuna"),
            MccEntry(544, countryCode = "AS", countryName = "American Samoa"),
            MccEntry(545, countryCode = "KI", countryName = "Kiribati"),
            MccEntry(546, countryCode = "NC", countryName = "New Caledonia"),
            MccEntry(547, countryCode = "PF", countryName = "French Polynesia"),
            MccEntry(548, countryCode = "CK", countryName = "Cook Islands"),
            MccEntry(549, countryCode = "WS", countryName = "Samoa"),
            MccEntry(550, countryCode = "FM", countryName = "Micronesia"),
            MccEntry(551, countryCode = "MH", countryName = "Marshall Islands"),
            MccEntry(552, countryCode = "PW", countryName = "Palau"),
            MccEntry(553, countryCode = "TV", countryName = "Tuvalu"),
            MccEntry(555, countryCode = "NU", countryName = "Niue"),
            MccEntry(602, countryCode = "EG", countryName = "Egypt"),
            MccEntry(603, countryCode = "DZ", countryName = "Algeria"),
            MccEntry(604, countryCode = "MA", countryName = "Morocco"),
            MccEntry(605, countryCode = "TN", countryName = "Tunisia"),
            MccEntry(606, countryCode = "LY", countryName = "Libya"),
            MccEntry(607, countryCode = "GM", countryName = "Gambia"),
            MccEntry(608, countryCode = "SN", countryName = "Senegal"),
            MccEntry(609, countryCode = "MR", countryName = "Mauritania"),
            MccEntry(610, countryCode = "ML", countryName = "Mali"),
            MccEntry(611, countryCode = "GN", countryName = "Guinea"),
            MccEntry(612, countryCode = "CI", countryName = "Côte d'Ivoire"),
            MccEntry(613, countryCode = "BF", countryName = "Burkina Faso"),
            MccEntry(614, countryCode = "NE", countryName = "Niger"),
            MccEntry(615, countryCode = "TG", countryName = "Togo"),
            MccEntry(616, countryCode = "BJ", countryName = "Benin"),
            MccEntry(617, countryCode = "MU", countryName = "Mauritius"),
            MccEntry(618, countryCode = "LR", countryName = "Liberia"),
            MccEntry(619, countryCode = "SL", countryName = "Sierra Leone"),
            MccEntry(620, countryCode = "GH", countryName = "Ghana"),
            MccEntry(621, countryCode = "NG", countryName = "Nigeria"),
            MccEntry(622, countryCode = "TD", countryName = "Chad"),
            MccEntry(623, countryCode = "CF", countryName = "Central African Republic"),
            MccEntry(624, countryCode = "CM", countryName = "Cameroon"),
            MccEntry(625, countryCode = "CV", countryName = "Cape Verde"),
            MccEntry(626, countryCode = "ST", countryName = "São Tomé and Príncipe"),
            MccEntry(627, countryCode = "GQ", countryName = "Equatorial Guinea"),
            MccEntry(628, countryCode = "GA", countryName = "Gabon"),
            MccEntry(629, countryCode = "CG", countryName = "Republic of the Congo"),
            MccEntry(630, countryCode = "CD", countryName = "Democratic Republic of the Congo"),
            MccEntry(631, countryCode = "AO", countryName = "Angola"),
            MccEntry(632, countryCode = "GW", countryName = "Guinea-Bissau"),
            MccEntry(633, countryCode = "SC", countryName = "Seychelles"),
            MccEntry(634, countryCode = "SD", countryName = "Sudan"),
            MccEntry(635, countryCode = "RW", countryName = "Rwanda"),
            MccEntry(636, countryCode = "ET", countryName = "Ethiopia"),
            MccEntry(637, countryCode = "SO", countryName = "Somalia"),
            MccEntry(638, countryCode = "DJ", countryName = "Djibouti"),
            MccEntry(639, countryCode = "KE", countryName = "Kenya"),
            MccEntry(640, countryCode = "TZ", countryName = "Tanzania"),
            MccEntry(641, countryCode = "UG", countryName = "Uganda"),
            MccEntry(642, countryCode = "BI", countryName = "Burundi"),
            MccEntry(643, countryCode = "MZ", countryName = "Mozambique"),
            MccEntry(645, countryCode = "ZM", countryName = "Zambia"),
            MccEntry(646, countryCode = "MG", countryName = "Madagascar"),
            MccEntry(647, countryCode = "RE", countryName = "Réunion"),
            MccEntry(648, countryCode = "ZW", countryName = "Zimbabwe"),
            MccEntry(649, countryCode = "NA", countryName = "Namibia"),
            MccEntry(650, countryCode = "MW", countryName = "Malawi"),
            MccEntry(651, countryCode = "LS", countryName = "Lesotho"),
            MccEntry(652, countryCode = "BW", countryName = "Botswana"),
            MccEntry(653, countryCode = "SZ", countryName = "Eswatini"),
            MccEntry(654, countryCode = "KM", countryName = "Comoros"),
            MccEntry(655, countryCode = "ZA", countryName = "South Africa"),
            MccEntry(657, countryCode = "ER", countryName = "Eritrea"),
            MccEntry(658, countryCode = "SH", countryName = "Saint Helena"),
            MccEntry(659, countryCode = "SS", countryName = "South Sudan"),
            MccEntry(702, countryCode = "BZ", countryName = "Belize"),
            MccEntry(704, countryCode = "GT", countryName = "Guatemala"),
            MccEntry(706, countryCode = "SV", countryName = "El Salvador"),
            MccEntry(708, countryCode = "HN", countryName = "Honduras"),
            MccEntry(710, countryCode = "NI", countryName = "Nicaragua"),
            MccEntry(712, countryCode = "CR", countryName = "Costa Rica"),
            MccEntry(714, countryCode = "PA", countryName = "Panama"),
            MccEntry(716, countryCode = "PE", countryName = "Peru"),
            MccEntry(722, countryCode = "AR", countryName = "Argentina"),
            MccEntry(724, countryCode = "BR", countryName = "Brazil"),
            MccEntry(730, countryCode = "CL", countryName = "Chile"),
            MccEntry(732, countryCode = "CO", countryName = "Colombia"),
            MccEntry(734, countryCode = "VE", countryName = "Venezuela"),
            MccEntry(736, countryCode = "BO", countryName = "Bolivia"),
            MccEntry(738, countryCode = "GY", countryName = "Guyana"),
            MccEntry(740, countryCode = "EC", countryName = "Ecuador"),
            MccEntry(742, countryCode = "GF", countryName = "French Guiana"),
            MccEntry(744, countryCode = "PY", countryName = "Paraguay"),
            MccEntry(746, countryCode = "SR", countryName = "Suriname"),
            MccEntry(748, countryCode = "UY", countryName = "Uruguay"),
            MccEntry(750, countryCode = "FK", countryName = "Falkland Islands"),
            MccEntry(901, countryCode = "EU", countryName = "International Networks")
        )
    }

    fun getEntries(): List<MccEntry> = entries_

    fun getCountryName(mcc: Int): String =
        entries_.firstOrNull { it.mcc == mcc }?.countryName ?: "Unknown"

    fun getCountryCode(mcc: Int): String =
        entries_.firstOrNull { it.mcc == mcc }?.countryCode ?: "UNKNOWN"
}
