package com.roamguard.common.util

object MccCountryMapper {
    private val mccMap = mapOf(
        202 to "GR",
        204 to "NL",
        206 to "BE",
        208 to "FR",
        212 to "MC",
        213 to "AD",
        214 to "ES",
        216 to "HU",
        218 to "BA",
        219 to "HR",
        220 to "RS",
        222 to "IT",
        225 to "VA",
        226 to "RO",
        228 to "CH",
        230 to "CZ",
        231 to "SK",
        232 to "AT",
        234 to "GB",
        235 to "GB",
        238 to "DK",
        240 to "SE",
        242 to "NO",
        244 to "FI",
        246 to "LT",
        247 to "LV",
        248 to "EE",
        250 to "RU",
        255 to "UA",
        257 to "BY",
        259 to "MD",
        260 to "PL",
        262 to "DE",
        266 to "GI",
        268 to "PT",
        270 to "LU",
        272 to "IE",
        274 to "IS",
        276 to "AL",
        278 to "MT",
        280 to "CY",
        282 to "GE",
        283 to "AM",
        284 to "BG",
        286 to "TR",
        288 to "FO",
        290 to "GL",
        292 to "SM",
        293 to "SI",
        294 to "MK",
        295 to "LI",
        297 to "ME",
        302 to "CA",
        308 to "PM",
        310 to "US",
        311 to "US",
        312 to "US",
        313 to "US",
        314 to "US",
        315 to "US",
        316 to "US",
        330 to "PR",
        332 to "VI",
        334 to "MX",
        338 to "JM",
        340 to "GP",
        342 to "BB",
        344 to "AG",
        346 to "KY",
        348 to "VG",
        350 to "BM",
        352 to "GD",
        354 to "MS",
        356 to "KN",
        358 to "LC",
        360 to "VC",
        362 to "AI",
        363 to "AW",
        364 to "BS",
        365 to "AI",
        366 to "DM",
        368 to "CU",
        370 to "DO",
        372 to "HT",
        374 to "TT",
        376 to "TC",
        400 to "AZ",
        401 to "KZ",
        402 to "BT",
        404 to "IN",
        405 to "IN",
        406 to "IN",
        410 to "PK",
        412 to "AF",
        413 to "LK",
        414 to "MM",
        415 to "LB",
        416 to "JO",
        417 to "SY",
        418 to "IQ",
        419 to "KW",
        420 to "SA",
        421 to "YE",
        422 to "OM",
        423 to "PS",
        424 to "AE",
        425 to "IL",
        426 to "BH",
        427 to "QA",
        428 to "MN",
        429 to "NP",
        430 to "AE",
        431 to "AE",
        432 to "IR",
        434 to "UZ",
        436 to "TJ",
        437 to "KG",
        438 to "TM",
        440 to "JP",
        441 to "JP",
        450 to "KR",
        452 to "VN",
        454 to "HK",
        455 to "MO",
        456 to "KH",
        457 to "LA",
        460 to "CN",
        461 to "CN",
        466 to "TW",
        467 to "KP",
        470 to "BD",
        472 to "MV",
        502 to "MY",
        505 to "AU",
        510 to "ID",
        514 to "TL",
        515 to "PH",
        520 to "TH",
        525 to "SG",
        528 to "BN",
        530 to "NZ",
        536 to "NR",
        537 to "PG",
        539 to "TO",
        540 to "SB",
        541 to "VU",
        542 to "FJ",
        543 to "WF",
        544 to "AS",
        545 to "KI",
        546 to "NC",
        547 to "PF",
        548 to "CK",
        549 to "WS",
        550 to "FM",
        551 to "MH",
        552 to "PW",
        553 to "TV",
        555 to "NU",
        602 to "EG",
        603 to "DZ",
        604 to "MA",
        605 to "TN",
        606 to "LY",
        607 to "GM",
        608 to "SN",
        609 to "MR",
        610 to "ML",
        611 to "GN",
        612 to "CI",
        613 to "BF",
        614 to "NE",
        615 to "TG",
        616 to "BJ",
        617 to "MU",
        618 to "LR",
        619 to "SL",
        620 to "GH",
        621 to "NG",
        622 to "TD",
        623 to "CF",
        624 to "CM",
        625 to "CV",
        626 to "ST",
        627 to "GQ",
        628 to "GA",
        629 to "CG",
        630 to "CD",
        631 to "AO",
        632 to "GW",
        633 to "SC",
        634 to "SD",
        635 to "RW",
        636 to "ET",
        637 to "SO",
        638 to "DJ",
        639 to "KE",
        640 to "TZ",
        641 to "UG",
        642 to "BI",
        643 to "MZ",
        645 to "ZM",
        646 to "MG",
        647 to "RE",
        648 to "ZW",
        649 to "NA",
        650 to "MW",
        651 to "LS",
        652 to "BW",
        653 to "SZ",
        654 to "KM",
        655 to "ZA",
        657 to "ER",
        658 to "SH",
        659 to "SS",
        702 to "BZ",
        704 to "GT",
        706 to "SV",
        708 to "HN",
        710 to "NI",
        712 to "CR",
        714 to "PA",
        716 to "PE",
        722 to "AR",
        724 to "BR",
        730 to "CL",
        732 to "CO",
        734 to "VE",
        736 to "BO",
        738 to "GY",
        740 to "EC",
        742 to "GF",
        744 to "PY",
        746 to "SR",
        748 to "UY",
        750 to "FK",
        901 to "EU"
    )

    private val countryNames = mapOf(
        "GR" to "Greece",
        "NL" to "Netherlands",
        "BE" to "Belgium",
        "FR" to "France",
        "MC" to "Monaco",
        "AD" to "Andorra",
        "ES" to "Spain",
        "HU" to "Hungary",
        "BA" to "Bosnia and Herzegovina",
        "HR" to "Croatia",
        "RS" to "Serbia",
        "IT" to "Italy",
        "VA" to "Vatican City",
        "RO" to "Romania",
        "CH" to "Switzerland",
        "CZ" to "Czech Republic",
        "SK" to "Slovakia",
        "AT" to "Austria",
        "GB" to "United Kingdom",
        "DK" to "Denmark",
        "SE" to "Sweden",
        "NO" to "Norway",
        "FI" to "Finland",
        "LT" to "Lithuania",
        "LV" to "Latvia",
        "EE" to "Estonia",
        "RU" to "Russia",
        "UA" to "Ukraine",
        "BY" to "Belarus",
        "MD" to "Moldova",
        "PL" to "Poland",
        "DE" to "Germany",
        "GI" to "Gibraltar",
        "PT" to "Portugal",
        "LU" to "Luxembourg",
        "IE" to "Ireland",
        "IS" to "Iceland",
        "AL" to "Albania",
        "MT" to "Malta",
        "CY" to "Cyprus",
        "GE" to "Georgia",
        "AM" to "Armenia",
        "BG" to "Bulgaria",
        "TR" to "Turkey",
        "FO" to "Faroe Islands",
        "GL" to "Greenland",
        "SM" to "San Marino",
        "SI" to "Slovenia",
        "MK" to "North Macedonia",
        "LI" to "Liechtenstein",
        "ME" to "Montenegro",
        "CA" to "Canada",
        "PM" to "Saint Pierre and Miquelon",
        "US" to "United States",
        "PR" to "Puerto Rico",
        "VI" to "U.S. Virgin Islands",
        "MX" to "Mexico",
        "JM" to "Jamaica",
        "GP" to "Guadeloupe",
        "BB" to "Barbados",
        "AG" to "Antigua and Barbuda",
        "KY" to "Cayman Islands",
        "VG" to "British Virgin Islands",
        "BM" to "Bermuda",
        "GD" to "Grenada",
        "MS" to "Montserrat",
        "KN" to "Saint Kitts and Nevis",
        "LC" to "Saint Lucia",
        "VC" to "Saint Vincent and the Grenadines",
        "AI" to "Anguilla",
        "AW" to "Aruba",
        "BS" to "Bahamas",
        "DM" to "Dominica",
        "CU" to "Cuba",
        "DO" to "Dominican Republic",
        "HT" to "Haiti",
        "TT" to "Trinidad and Tobago",
        "TC" to "Turks and Caicos Islands",
        "AZ" to "Azerbaijan",
        "KZ" to "Kazakhstan",
        "BT" to "Bhutan",
        "IN" to "India",
        "PK" to "Pakistan",
        "AF" to "Afghanistan",
        "LK" to "Sri Lanka",
        "MM" to "Myanmar",
        "LB" to "Lebanon",
        "JO" to "Jordan",
        "SY" to "Syria",
        "IQ" to "Iraq",
        "KW" to "Kuwait",
        "SA" to "Saudi Arabia",
        "YE" to "Yemen",
        "OM" to "Oman",
        "PS" to "Palestine",
        "AE" to "United Arab Emirates",
        "IL" to "Israel",
        "BH" to "Bahrain",
        "QA" to "Qatar",
        "MN" to "Mongolia",
        "NP" to "Nepal",
        "IR" to "Iran",
        "UZ" to "Uzbekistan",
        "TJ" to "Tajikistan",
        "KG" to "Kyrgyzstan",
        "TM" to "Turkmenistan",
        "JP" to "Japan",
        "KR" to "South Korea",
        "VN" to "Vietnam",
        "HK" to "Hong Kong",
        "MO" to "Macau",
        "KH" to "Cambodia",
        "LA" to "Laos",
        "CN" to "China",
        "TW" to "Taiwan",
        "KP" to "North Korea",
        "BD" to "Bangladesh",
        "MV" to "Maldives",
        "MY" to "Malaysia",
        "AU" to "Australia",
        "ID" to "Indonesia",
        "TL" to "Timor-Leste",
        "PH" to "Philippines",
        "TH" to "Thailand",
        "SG" to "Singapore",
        "BN" to "Brunei",
        "NZ" to "New Zealand",
        "NR" to "Nauru",
        "PG" to "Papua New Guinea",
        "TO" to "Tonga",
        "SB" to "Solomon Islands",
        "VU" to "Vanuatu",
        "FJ" to "Fiji",
        "WF" to "Wallis and Futuna",
        "AS" to "American Samoa",
        "KI" to "Kiribati",
        "NC" to "New Caledonia",
        "PF" to "French Polynesia",
        "CK" to "Cook Islands",
        "WS" to "Samoa",
        "FM" to "Micronesia",
        "MH" to "Marshall Islands",
        "PW" to "Palau",
        "TV" to "Tuvalu",
        "NU" to "Niue",
        "EG" to "Egypt",
        "DZ" to "Algeria",
        "MA" to "Morocco",
        "TN" to "Tunisia",
        "LY" to "Libya",
        "GM" to "Gambia",
        "SN" to "Senegal",
        "MR" to "Mauritania",
        "ML" to "Mali",
        "GN" to "Guinea",
        "CI" to "Côte d'Ivoire",
        "BF" to "Burkina Faso",
        "NE" to "Niger",
        "TG" to "Togo",
        "BJ" to "Benin",
        "MU" to "Mauritius",
        "LR" to "Liberia",
        "SL" to "Sierra Leone",
        "GH" to "Ghana",
        "NG" to "Nigeria",
        "TD" to "Chad",
        "CF" to "Central African Republic",
        "CM" to "Cameroon",
        "CV" to "Cape Verde",
        "ST" to "São Tomé and Príncipe",
        "GQ" to "Equatorial Guinea",
        "GA" to "Gabon",
        "CG" to "Republic of the Congo",
        "CD" to "Democratic Republic of the Congo",
        "AO" to "Angola",
        "GW" to "Guinea-Bissau",
        "SC" to "Seychelles",
        "SD" to "Sudan",
        "RW" to "Rwanda",
        "ET" to "Ethiopia",
        "SO" to "Somalia",
        "DJ" to "Djibouti",
        "KE" to "Kenya",
        "TZ" to "Tanzania",
        "UG" to "Uganda",
        "BI" to "Burundi",
        "MZ" to "Mozambique",
        "ZM" to "Zambia",
        "MG" to "Madagascar",
        "RE" to "Réunion",
        "ZW" to "Zimbabwe",
        "NA" to "Namibia",
        "MW" to "Malawi",
        "LS" to "Lesotho",
        "BW" to "Botswana",
        "SZ" to "Eswatini",
        "KM" to "Comoros",
        "ZA" to "South Africa",
        "ER" to "Eritrea",
        "SH" to "Saint Helena",
        "SS" to "South Sudan",
        "BZ" to "Belize",
        "GT" to "Guatemala",
        "SV" to "El Salvador",
        "HN" to "Honduras",
        "NI" to "Nicaragua",
        "CR" to "Costa Rica",
        "PA" to "Panama",
        "PE" to "Peru",
        "AR" to "Argentina",
        "BR" to "Brazil",
        "CL" to "Chile",
        "CO" to "Colombia",
        "VE" to "Venezuela",
        "BO" to "Bolivia",
        "GY" to "Guyana",
        "EC" to "Ecuador",
        "GF" to "French Guiana",
        "PY" to "Paraguay",
        "SR" to "Suriname",
        "UY" to "Uruguay",
        "FK" to "Falkland Islands",
        "EU" to "International Networks"
    )

    private val countryNamesDe = mapOf(
        "GR" to "Griechenland",
        "NL" to "Niederlande",
        "BE" to "Belgien",
        "FR" to "Frankreich",
        "ES" to "Spanien",
        "IT" to "Italien",
        "GB" to "Vereinigtes Königreich",
        "DE" to "Deutschland",
        "AT" to "Österreich",
        "CH" to "Schweiz",
        "PL" to "Polen",
        "CZ" to "Tschechien",
        "SK" to "Slowakei",
        "HU" to "Ungarn",
        "RO" to "Rumänien",
        "BG" to "Bulgarien",
        "RS" to "Serbien",
        "HR" to "Kroatien",
        "SI" to "Slowenien",
        "DK" to "Dänemark",
        "SE" to "Schweden",
        "NO" to "Norwegen",
        "FI" to "Finnland",
        "PT" to "Portugal",
        "IE" to "Irland",
        "US" to "Vereinigte Staaten",
        "CA" to "Kanada",
        "MX" to "Mexiko",
        "JP" to "Japan",
        "CN" to "China",
        "IN" to "Indien",
        "KR" to "Südkorea",
        "BR" to "Brasilien",
        "AR" to "Argentinien",
        "CL" to "Chile",
        "AU" to "Australien",
        "NZ" to "Neuseeland",
        "ZA" to "Südafrika",
        "RU" to "Russland",
        "TR" to "Türkei",
        "UA" to "Ukraine",
        "EG" to "Ägypten",
        "IL" to "Israel",
        "AE" to "Vereinigte Arabische Emirate",
        "SA" to "Saudi-Arabien",
        "SG" to "Singapur",
        "MY" to "Malaysia",
        "TH" to "Thailand",
        "ID" to "Indonesien",
        "PH" to "Philippinen",
        "VN" to "Vietnam",
        "HK" to "Hongkong",
        "TW" to "Taiwan",
        "BD" to "Bangladesch",
        "PK" to "Pakistan",
        "IR" to "Iran",
        "IQ" to "Irak",
        "KZ" to "Kasachstan",
        "EG" to "Ägypten",
        "MA" to "Marokko",
        "DZ" to "Algerien",
        "TN" to "Tunesien",
        "NG" to "Nigeria",
        "KE" to "Kenia",
        "ET" to "Äthiopien",
        "TZ" to "Tansania",
        "GH" to "Ghana",
        "CM" to "Kamerun",
        "CI" to "Elfenbeinküste",
        "SN" to "Senegal",
        "ML" to "Mali",
        "AO" to "Angola",
        "MZ" to "Mosambik",
        "ZM" to "Sambia",
        "ZW" to "Simbabwe",
        "MW" to "Malawi",
        "UG" to "Uganda",
        "RW" to "Ruanda",
        "SD" to "Sudan",
        "SS" to "Südsudan",
        "SO" to "Somalia",
        "CD" to "Demokratische Republik Kongo",
        "CG" to "Republik Kongo",
        "GA" to "Gabun",
        "GQ" to "Äquatorialguinea",
        "BJ" to "Benin",
        "BF" to "Burkina Faso",
        "NE" to "Niger",
        "TD" to "Tschad",
        "CF" to "Zentralafrikanische Republik",
        "TG" to "Togo",
        "SL" to "Sierra Leone",
        "LR" to "Liberia",
        "MR" to "Mauretanien",
        "GM" to "Gambia",
        "GW" to "Guinea-Bissau",
        "GN" to "Guinea",
        "ER" to "Eritrea",
        "DJ" to "Dschibuti",
        "BI" to "Burundi",
        "LS" to "Lesotho",
        "BW" to "Botswana",
        "NA" to "Namibia",
        "SZ" to "Eswatini",
        "KM" to "Komoren",
        "SC" to "Seychellen",
        "MU" to "Mauritius",
        "CV" to "Kap Verde",
        "ST" to "São Tomé und Príncipe",
        "SH" to "St. Helena",
        "GM" to "Gambia"
    )

    fun getCountryCode(mcc: Int): String = mccMap[mcc] ?: "UNKNOWN"
    fun getCountryName(mcc: Int): String = countryNames[getCountryCode(mcc)] ?: "Unknown"
    fun getCountryNameDe(mcc: Int): String = countryNamesDe[getCountryCode(mcc)] ?: getCountryName(mcc)
    fun getAllMccEntries(): List<MccEntry> = mccMap.map { (mcc, code) ->
        MccEntry(mcc = mcc, countryCode = code, countryName = countryNames[code] ?: code)
    }.sortedBy { it.countryName }

    data class MccEntry(
        val mcc: Int,
        val countryCode: String,
        val countryName: String
    )
}
